### ISSUE TITLE
Criar protótipo de alta fidelidade da tela de Dashboard

### ISSUE THREAD

**Issue by wescleymatos** [Indra-JPs/gitlab-plus#5]
## Segue alguns indicadores
 - Total de telas geral
 - total de telas da sprint
 - total de issues em RP
 - total de issues em Stating	
 - total de issues em Todo

**Comment by PauloRenato98** [comment]
To na área

**Comment by PauloRenato98** [comment]
![image](https://user-images.githubusercontent.com/48812145/77501157-e014c100-6e35-11ea-9b99-9654a141c50e.png)

A primeira versão ficou assim.

**Comment by PauloRenato98** [comment]
![image](https://user-images.githubusercontent.com/48812145/77601757-612d9000-6eea-11ea-8e8c-50c824985e1c.png)
A segunda versão ficou assim.

**Comment by PauloRenato98** [comment]
![image](https://user-images.githubusercontent.com/48812145/77602373-13198c00-6eec-11ea-9347-854054ab4649.png)


A segunda versão ficou assim.

**Comment by wandessonsoares** [comment]
Reformulado.

https://www.figma.com/file/4KftEQL0DTVO58iE38yzGm/Untitled?node-id=0%3A1

**Comment by PauloRenato98** [comment]
![image](https://user-images.githubusercontent.com/48812145/78084019-80666a80-738d-11ea-87a3-5fcf0bece009.png)
