### ISSUE TITLE
Criar página de login com condiguração de autenticação

### ISSUE THREAD

**Issue by wescleymatos** [Indra-JPs/gitlab-plus#53]

**Comment by rodrigodan** [comment]
**Rodrigo Gonçalves:**
**Minha task:**
- Fiz validação de autenticação, onde o suário não logado, será sempre redirecionado para a tela de login;

- Usuário uma vez logado, será redirecionado para a tela de dashboard e terá liberdade para acessar qualquer outra tela;

- Para fazer os dois itens acima, usei as features Guards e Forms do Angular e Injeção de dependência para construção de dois serviços: AuthGuard que gerencia os Guards e AuthService para autenticação do Login.

**Sugestão feita ao desenvolvedor @tjeveraldo que tava travalhando com o layout da tela de login:**
- Quanto ao background, sugeri a retirada da cor azul do login;

- Sugeri a substituição da imagem antiga do card do login por um ícone de usuário. Esse ícone poderia vir de uma lib importada ou de um arquivo de imagem png ou svg:
Exemplo de ícone:
![image](https://user-images.githubusercontent.com/16531089/79298104-7fb5f400-7eb6-11ea-8a35-1052eb0888aa.png)

- Redução do tamanho do Card de modo que ele ficasse mais verticalizado. 

- Moldar novamente o tamanho do Card de modo que ele permanecesse verticalizado, mas sem a barra de rolagem vertical.
