### ISSUE TITLE
Criação do protótipo de alta fidelidade da tela de issues

### ISSUE THREAD

**Issue by wescleymatos** [Indra-JPs/gitlab-plus#6]
## Sugestão para a tela
- Grid com a issues  
  - filtro por sprint
  - filtro por label
  - filtro por usuário

## Funcionalidade adicionais
- exportar excel
- label para visualizar tempo gasto em horas X estimativa

**Comment by rodrigodan** [comment]
https://www.figma.com/file/dQjm26xWGGNxtpgwKoo8sw/Issues

![image](https://user-images.githubusercontent.com/16531089/78091572-9d0d9d00-73a3-11ea-8f7a-c99f23728eca.png)

**Comment by rodrigodan** [comment]
https://www.figma.com/file/dQjm26xWGGNxtpgwKoo8sw/Issues?node-id=0%3A1

![image](https://user-images.githubusercontent.com/16531089/78314050-1be31100-752f-11ea-90e4-c846f20d47e2.png)

**Comment by wandessonsoares** [comment]
**Melhorias**

- Ajustar cores
- Inserir dados mais próximos do real na coluna issue
- Ajustar alinhamento
- Equanimizar tamanho dos botões
- Ajustar dados e layout dos dropdowns
- Colocar "Filtrar issues" como fieldset
- Diminuir espaço entre os títulos das colunas do grip e o próprio grid

**Comment by rodrigodan** [comment]
![image](https://user-images.githubusercontent.com/16531089/78321751-3921da80-7543-11ea-9027-348ad85b7747.png)

**Comment by rodrigodan** [comment]
![image](https://user-images.githubusercontent.com/16531089/78322275-a71ad180-7544-11ea-83bf-d2fae776fcec.png)
