### ISSUE TITLE
Criar protótipo de alta fidelidade da tela do gráfico de burndown

### ISSUE THREAD

**Issue by wescleymatos** [Indra-JPs/gitlab-plus#7]
## Sugestão

- Exibir gráfico a partir do filtro por sprint

**Comment by EmilianoFreitas** [comment]
![image](https://user-images.githubusercontent.com/21049651/77501272-48fc3900-6e36-11ea-84b0-79cc0d104a0d.png)

Primeira versão da tela de Burndown

**Comment by wescleymatos** [comment]
Só senti falta do filtro por sprint.

**Comment by EmilianoFreitas** [comment]
Burndown versão 2.0

![image](https://user-images.githubusercontent.com/21049651/78318479-3327fb80-753b-11ea-880c-95b7fd20b370.png)
